#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-Everything
version:      0.03
version_from: Everything.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
